### ISSUE TITLE
Crate ownership?

### ISSUE THREAD

**Issue by Morganamilo** [derekdreery/alpm#17]
Hello, I have written my own alpm bindings for rust. And seems as there are already 4 different alpm bindings on cargo I would rather reuse one of the crates rather than upload another. So I am looking to take over some ones existing create.

This project has not seen a commit in a while so I'm not sure sure if this project is still alive. Would you be willing to give me ownership of the crate name for me to upload my own bindings to?

**Comment by richard-uk1** [comment]
Hi @Morganamilo 

I'd rather not change ownership of this crate, as it can be a source of problems for users (e.g. https://www.schneier.com/blog/archives/2018/11/distributing_ma.html). I'm also slowly working on a pure-rust implementation of alpm which I think should have this name (rather than say a name like `c-alpm` for bindings to the C library).

However, I'm more than happy to collaborate.

**Comment by Morganamilo** [comment]
I'm somewhat known in the arch community so no risk of me distributing malware :P 

But yeah, if you do have plans to use this crate in future then that's totally fair enough.

**Comment by richard-uk1** [comment]
I'm very keen to help out where I can, and I think rust can be really good for arch - maybe even for writing pacman (since it runs as root the safety guarantees are very attractive). I've also got some experience with alpm now so if you do some alpm work in rust and need some contribution, feel free to reach out to me.

**Comment by Morganamilo** [comment]
To revive this slightly. I have ownership of the `alpm` crate now. It would be nice to get `alpm-sys` to go with. Seems as you're plans are to eventually make a pure rust implementation you would no longer need that crate I assume?

**Comment by richard-uk1** [comment]
Hey, I'm not against this in principle. I would probably prefer joint ownership, but I'm not wedded to that.

**Comment by Morganamilo** [comment]
If you wanna do joint ownership I'm fine with that. I just want a sanely named crate to use.

**Comment by Morganamilo** [comment]
It's been a year, I'm still maintaining the alpm crate and have fully complete bindings. I don't know if you've just forgotten about this issue but I'm still interested if you're willing.

**Comment by richard-uk1** [comment]
Yeah let's transfer it over.

**Comment by richard-uk1** [comment]
Let me know what I need to do to transfer it to you.

**Comment by Morganamilo** [comment]
Thanks. My name over there is also Morganamilo. Just go to the crate and manage owners.

**Comment by richard-uk1** [comment]
Ok you should have had an invite. I'm happy to help maintaining the crate if you like.

**Comment by Morganamilo** [comment]
Thanks. Accepted, renamed alpm-sys-fork to alpm-sys and made alpm depend on it.

If you want to help maintain it then the repo is here https://github.com/Morganamilo/alpm.rs if you want to take a peek.
